name: receita
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  mask_text_input_formatter: ^2.9.0
  sqflite: ^2.4.1
  sqflite_common_ffi: any
  sqflite_common_ffi_web: ^0.4.5+4
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
